-- ═══════════════════════════════════════════════════════════════════
-- Sonic Pro — Supabase Database Migration
-- Run this in: Supabase Dashboard → SQL Editor → New query
-- ═══════════════════════════════════════════════════════════════════
-- 
-- Schema design rationale:
--   Core metrics as typed columns — enables future SQL queries, filters,
--   and indexes (e.g. "find all saves louder than -9 LUFS").
--   Full analysis blob as JSONB — flexible, schema-free, allows adding
--   new fields (vibe timeline, flatness, etc.) without migrations.
--
-- Security: Row Level Security (RLS) is enabled. ALL access is enforced
-- at the database level via `auth.uid() = user_id`. There are no
-- client-side security checks — the DB is the single source of truth.
-- ═══════════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────────────────
-- 1. CREATE TABLE
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.analyses (
  -- Primary key — generated by Supabase, never client-supplied
  id              uuid          PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Owner — set to the authenticated user's ID at insert time.
  -- References auth.users so orphaned rows are cleaned up on account deletion.
  user_id         uuid          NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Timestamp — stored in UTC, displayed in client's local timezone
  created_at      timestamptz   NOT NULL DEFAULT now(),

  -- ── Indexed scalar metrics (enables future filtering / sorting) ──────────
  -- File name of the uploaded mix (display only — no path, no audio data)
  file_name       text          NOT NULL DEFAULT '',

  -- EBU R128 Integrated Loudness in LUFS — most commonly queried metric
  integrated_lufs float         NULL,

  -- True peak in dBFS
  peak_db         float         NULL,

  -- Crest factor (peak - RMS) in dB — proxy for dynamic range
  crest_factor    float         NULL,

  -- Genre profile ID used during comparison ("edm", "pop", "hiphop", etc.)
  -- NULL = reference track comparison was used, no genre profile selected
  profile_id      text          NULL,

  -- ── Full analysis payload (JSONB) ────────────────────────────────────────
  -- Contains: mixHealth, vibeTimeline, delta, referenceTrack, selectedProfile
  -- Stored as-is from the client; never parsed server-side.
  full_data       jsonb         NOT NULL DEFAULT '{}'::jsonb
);

-- Human-readable comment on the table
COMMENT ON TABLE public.analyses IS
  'Sonic Pro mix analysis snapshots. Each row is one saved analysis by one user.';

COMMENT ON COLUMN public.analyses.full_data IS
  'Complete JSON analysis snapshot including mix health, vibe timeline, and delta bands.';


-- ─────────────────────────────────────────────────────────────
-- 2. INDEXES
-- ─────────────────────────────────────────────────────────────

-- Most queries filter by user first — this index is used in every RLS policy
CREATE INDEX IF NOT EXISTS analyses_user_id_idx
  ON public.analyses (user_id);

-- Sorting the library by newest first
CREATE INDEX IF NOT EXISTS analyses_created_at_idx
  ON public.analyses (user_id, created_at DESC);

-- Filter by genre profile (future: "show me all my EDM analyses")
CREATE INDEX IF NOT EXISTS analyses_profile_id_idx
  ON public.analyses (user_id, profile_id)
  WHERE profile_id IS NOT NULL;

-- Filter by loudness (future: "find my mixes above -14 LUFS")
CREATE INDEX IF NOT EXISTS analyses_integrated_lufs_idx
  ON public.analyses (user_id, integrated_lufs)
  WHERE integrated_lufs IS NOT NULL;


-- ─────────────────────────────────────────────────────────────
-- 3. ENABLE ROW LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────

-- RLS must be explicitly enabled — Supabase tables are public by default.
-- After ALTER TABLE ... ENABLE ROW LEVEL SECURITY, all access is DENIED
-- unless a policy explicitly allows it.
ALTER TABLE public.analyses ENABLE ROW LEVEL SECURITY;


-- ─────────────────────────────────────────────────────────────
-- 4. RLS POLICIES
-- ─────────────────────────────────────────────────────────────
--
-- Policy design: each policy covers exactly one operation type.
-- The predicate `auth.uid() = user_id` ensures users can ONLY ever
-- read or modify their own rows, regardless of client-side code.
--
-- auth.uid() returns NULL for anonymous/unauthenticated requests,
-- which never equals a valid UUID — so unauthenticated users are
-- automatically blocked from all operations without additional checks.


-- SELECT: users can read only their own analyses
CREATE POLICY "Users can view their own analyses"
  ON public.analyses
  FOR SELECT
  USING (auth.uid() = user_id);

-- INSERT: users can only insert rows where user_id matches their own UID.
-- The WITH CHECK clause prevents clients from setting user_id to another user's ID.
CREATE POLICY "Users can insert their own analyses"
  ON public.analyses
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- UPDATE: users can only update their own rows
CREATE POLICY "Users can update their own analyses"
  ON public.analyses
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- DELETE: users can only delete their own rows
CREATE POLICY "Users can delete their own analyses"
  ON public.analyses
  FOR DELETE
  USING (auth.uid() = user_id);


-- ─────────────────────────────────────────────────────────────
-- 5. ENFORCE 20-ROW LIMIT VIA DATABASE TRIGGER (Free Tier)
-- ─────────────────────────────────────────────────────────────
-- The client also enforces this, but this trigger is the authoritative
-- server-side limit. Active for free tier users.
--
CREATE OR REPLACE FUNCTION check_analysis_limit()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF (
    SELECT count(*) FROM public.analyses WHERE user_id = NEW.user_id
  ) >= 20 THEN
    RAISE EXCEPTION 'Analysis limit reached (20 maximum per tier). Delete an existing analysis to save a new one.';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER enforce_analysis_limit
  BEFORE INSERT ON public.analyses
  FOR EACH ROW EXECUTE FUNCTION check_analysis_limit();


-- ─────────────────────────────────────────────────────────────
-- 5b. PREVENT LARGE DATA STORAGE (200KB max for full_data JSONB)
-- ─────────────────────────────────────────────────────────────
-- Prevents accidental/malicious storage bloat from large analysis arrays.
-- Free tier caps analysis data at 200KB to prevent abuse.
--
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'analyses_full_data_size_check'
  ) THEN
    ALTER TABLE public.analyses
    ADD CONSTRAINT analyses_full_data_size_check
    CHECK (octet_length(full_data::text) <= 200000);
  END IF;
END;
$$;


-- ─────────────────────────────────────────────────────────────
-- 6. VERIFY — Run this SELECT to confirm RLS is active
-- ─────────────────────────────────────────────────────────────

SELECT
  schemaname,
  tablename,
  rowsecurity AS rls_enabled
FROM pg_tables
WHERE schemaname = 'public' AND tablename = 'analyses';

-- Expected output:
--  schemaname | tablename | rls_enabled
-- ────────────┼───────────┼─────────────
--  public     | analyses  | t
